language: node_js
node_js:
  - "5.6"
before_script:
  - npm install -g knex
  - psql -c 'create database test;' -U postgres
  - npm run migrate
script:
  - npm run test
  - npm install -g eslint-config-airbnb
  - npm install -g eslint-plugin-react
  - npm run lint
addons: 
  postgresql: "9.3"
services:
  - postgresql
